Document: libfastcommon
Title: Debian libfastcommon Manual
Author: <insert document author here>
Abstract: This manual describes what libfastcommon is
 and how it can be used to
 manage online manuals on Debian systems.
Section: zhangchunsheng

Format: debiandoc-sgml
Files: /usr/share/doc/libfastcommon/libfastcommon.sgml.gz

Format: postscript
Files: /usr/share/doc/libfastcommon/libfastcommon.ps.gz

Format: text
Files: /usr/share/doc/libfastcommon/libfastcommon.text.gz

Format: HTML
Index: /usr/share/doc/libfastcommon/html/index.html
Files: /usr/share/doc/libfastcommon/html/*.html
